//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnGiang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccChamCong
    {
        public long IDChamCong { get; set; }
        public Nullable<long> NguoiChamID { get; set; }
        public Nullable<long> NhanVienID { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public Nullable<int> SoNgayNghi { get; set; }
        public Nullable<double> AnTrua { get; set; }
        public Nullable<double> HuongLuong { get; set; }
        public Nullable<double> PhepNam { get; set; }
        public Nullable<double> BHXH_DuongSuc { get; set; }
        public Nullable<double> BHXH_KhamThai { get; set; }
        public Nullable<double> BHXH_ChamConBenh { get; set; }
        public Nullable<double> BHXH_NghiBenh { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public int DaXoa { get; set; }
        public Nullable<double> NgayPhep { get; set; }
    }
}
