//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnGiang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccChamCong
    {
        public long IDChamCong { get; set; }
        public Nullable<System.DateTime> NgayNghi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<long> NhanVienID { get; set; }
        public Nullable<long> KyHieuID { get; set; }
        public Nullable<long> NguoiChamID { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ccKyHieu ccKyHieu { get; set; }
        public virtual nvNhanVien nvNhanVien { get; set; }
    }
}
