//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnGiang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccChiTiet
    {
        public long IDChiTiet { get; set; }
        public Nullable<long> KyHieuID { get; set; }
        public Nullable<long> ChamCongID { get; set; }
        public Nullable<int> Ngay { get; set; }
        public Nullable<double> HuongLuong { get; set; }
        public Nullable<double> AnTrua { get; set; }
        public Nullable<double> PhepNam { get; set; }
        public Nullable<int> NgayNghi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> DaXoa { get; set; }
        public Nullable<double> NgayPhep { get; set; }
    }
}
