//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnGiang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccKyHieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ccKyHieu()
        {
            this.ccChamCongs = new HashSet<ccChamCong>();
        }
    
        public long IDKyHieu { get; set; }
        public string MaKyHieu { get; set; }
        public string TenKyHieu { get; set; }
        public Nullable<double> HuongLuong { get; set; }
        public Nullable<double> AnTrua { get; set; }
        public Nullable<double> PhepNam { get; set; }
        public string DienGiai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ccChamCong> ccChamCongs { get; set; }
    }
}
