//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnGiang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dvDonVi
    {
        public long IDDonVi { get; set; }
        public string MaDonVi { get; set; }
        public string TenDonVi { get; set; }
        public string MST { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Logo { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> DaXoa { get; set; }
    }
}
