//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnGiang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class lgBangLuong
    {
        public long IDChamCong { get; set; }
        public Nullable<int> TGPCKK { get; set; }
        public Nullable<double> HESOLUONG { get; set; }
        public Nullable<double> NGAYNGHI { get; set; }
        public Nullable<double> TIENLUONGPHEP { get; set; }
        public Nullable<double> HESOCHUCDANH { get; set; }
        public Nullable<int> PCKK { get; set; }
        public Nullable<int> NGAYCONG { get; set; }
        public Nullable<double> TIENLUONG { get; set; }
        public Nullable<double> TIENPCKK { get; set; }
        public Nullable<double> TIENLUONG100 { get; set; }
        public Nullable<double> TIENLUONG80 { get; set; }
        public Nullable<double> BHXH { get; set; }
        public Nullable<double> BHYT { get; set; }
        public Nullable<double> BHTN { get; set; }
        public Nullable<double> CDPHI { get; set; }
        public Nullable<double> DANGPHI { get; set; }
        public Nullable<double> THUCLANH { get; set; }
        public Nullable<double> LUONGCOBAN { get; set; }
        public string HOTEN { get; set; }
        public string TENCHUCDANH { get; set; }
        public string TENPHONGBAN { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<int> NAM { get; set; }
    }
}
