//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnGiang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nvChucDanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nvChucDanh()
        {
            this.nvChucVus = new HashSet<nvChucVu>();
        }
    
        public long IDChucDanh { get; set; }
        public string MaChucDanh { get; set; }
        public string TenChucDanh { get; set; }
        public Nullable<double> HeSoChucDanh { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> DaXoa { get; set; }
        public Nullable<long> PhongBanID { get; set; }
    
        public virtual dvPhongBan dvPhongBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nvChucVu> nvChucVus { get; set; }
    }
}
