//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnGiang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nvChucDanh
    {
        public nvChucDanh()
        {
            this.nvNhanViens = new HashSet<nvNhanVien>();
        }
    
        public long IDChucDanh { get; set; }
        public Nullable<long> DanhMucCDID { get; set; }
        public string MaChucDanh { get; set; }
        public string TenChucDanh { get; set; }
        public Nullable<double> HeSoChucDanh { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> DaXoa { get; set; }
    
        public virtual ICollection<nvNhanVien> nvNhanViens { get; set; }
    }
}
