//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnGiang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nvNhanVien
    {
        public long IDNhanVien { get; set; }
        public string MaNhanVien { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public string CMND { get; set; }
        public Nullable<double> HeSoLuong { get; set; }
        public Nullable<double> HeSoChucDanh { get; set; }
        public Nullable<int> TGPCKK { get; set; }
        public Nullable<int> DieuKienPCKK { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayLamViec { get; set; }
        public Nullable<System.DateTime> NgayNghiViec { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> DaXoa { get; set; }
        public Nullable<long> PhongBanID { get; set; }
        public Nullable<long> DonViID { get; set; }
        public Nullable<long> TrinhDoID { get; set; }
        public Nullable<long> ChucDanhID { get; set; }
    
        public virtual TrinhDo TrinhDo { get; set; }
        public virtual nvChucDanh nvChucDanh { get; set; }
    }
}
