//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnGiang.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AnGiangEntities : DbContext
    {
        public AnGiangEntities()
            : base("name=AnGiangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BacLuong> BacLuongs { get; set; }
        public virtual DbSet<ccChamCong> ccChamCongs { get; set; }
        public virtual DbSet<ccChiTiet> ccChiTiets { get; set; }
        public virtual DbSet<dvChuyenMon> dvChuyenMons { get; set; }
        public virtual DbSet<dvDonVi> dvDonVis { get; set; }
        public virtual DbSet<dvPhongBan> dvPhongBans { get; set; }
        public virtual DbSet<lskLoaiSuKien> lskLoaiSuKiens { get; set; }
        public virtual DbSet<lskSuKien> lskSuKiens { get; set; }
        public virtual DbSet<nvChucDanh> nvChucDanhs { get; set; }
        public virtual DbSet<nvChucVu> nvChucVus { get; set; }
        public virtual DbSet<nvNhanVien> nvNhanViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tlDinhMuc> tlDinhMucs { get; set; }
        public virtual DbSet<TrinhDo> TrinhDoes { get; set; }
        public virtual DbSet<ccKyHieu> ccKyHieux { get; set; }
    
        public virtual int pr_ThemChamCong(Nullable<long> iDNhanVien, Nullable<int> thang, Nullable<int> nam, Nullable<double> soNgay)
        {
            var iDNhanVienParameter = iDNhanVien.HasValue ?
                new ObjectParameter("IDNhanVien", iDNhanVien) :
                new ObjectParameter("IDNhanVien", typeof(long));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var soNgayParameter = soNgay.HasValue ?
                new ObjectParameter("SoNgay", soNgay) :
                new ObjectParameter("SoNgay", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_ThemChamCong", iDNhanVienParameter, thangParameter, namParameter, soNgayParameter);
        }
    
        public virtual int pr_ThemChiTiet(Nullable<long> iDKyHieu, Nullable<long> iDChamCong, Nullable<int> ngay)
        {
            var iDKyHieuParameter = iDKyHieu.HasValue ?
                new ObjectParameter("IDKyHieu", iDKyHieu) :
                new ObjectParameter("IDKyHieu", typeof(long));
    
            var iDChamCongParameter = iDChamCong.HasValue ?
                new ObjectParameter("IDChamCong", iDChamCong) :
                new ObjectParameter("IDChamCong", typeof(long));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_ThemChiTiet", iDKyHieuParameter, iDChamCongParameter, ngayParameter);
        }
    }
}
