//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnGiang.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnGiangEntities : DbContext
    {
        public AnGiangEntities()
            : base("name=AnGiangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BacLuong> BacLuongs { get; set; }
        public virtual DbSet<ccChamCong> ccChamCongs { get; set; }
        public virtual DbSet<ccKyHieu> ccKyHieux { get; set; }
        public virtual DbSet<dvChuyenMon> dvChuyenMons { get; set; }
        public virtual DbSet<dvDonVi> dvDonVis { get; set; }
        public virtual DbSet<dvPhongBan> dvPhongBans { get; set; }
        public virtual DbSet<lskLoaiSuKien> lskLoaiSuKiens { get; set; }
        public virtual DbSet<lskSuKien> lskSuKiens { get; set; }
        public virtual DbSet<nvChucDanh> nvChucDanhs { get; set; }
        public virtual DbSet<nvChucVu> nvChucVus { get; set; }
        public virtual DbSet<nvNhanVien> nvNhanViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tlDinhMuc> tlDinhMucs { get; set; }
        public virtual DbSet<TrinhDo> TrinhDoes { get; set; }
    }
}
