//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnGiang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrinhDo
    {
        public long IDTrinhDo { get; set; }
        public string MaTrinhDo { get; set; }
        public string TenTrinhDo { get; set; }
    }
}
